#!/bin/sh -
#
# Copyright (c) 2020 Shawn Webb <shawn.webb@hardenedbsd.org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

# PROVIDE: hbsdmon
# REQUIRE: NETWORK
# KEYWORD: shutdown

. /etc/rc.subr

name="hbsdmon"
rcvar="hbsdmon_enable"
start_precmd="hbsdmon_prestart"
start_cmd="hbsdmon_start"
stop_cmd="hbsdmon_stop"

load_rc_config $name
: ${hbsdmon_enable:="NO"}
: ${hbsdmon_conf:="/usr/local/etc/hbsdmon.conf"}
: ${hbsdmon_pidfile:="/var/run/hbsdmon.pid"}

hbsdmon_prestart()
{
	if [ -e ${hbsdmon_pidfile} ]; then
		echo "hbsdmon already started. Check ${hbsdmon_pidfile}"
		return 1
	fi
}

hbsdmon_start()
{
	/usr/sbin/daemon -p ${hbsdmon_pidfile} \
	    -f \
	    /usr/bin/hbsdmon -c ${hbsdmon_conf}
}

hbsdmon_stop()
{
	if [ -e ${hbsdmon_pidfile} ]; then
		kill -TERM $(cat ${hbsdmon_pidfile})
	fi
}

run_rc_command "$1"
